apiVersion: v1
kind: Service
metadata:
  name: {{ include "wg-easy.fullname" . }}-vpn
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
  {{- with .Values.service.vpn.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.vpn.type }}
  {{- if contains "LoadBalancer" .Values.service.vpn.type }}
  externalTrafficPolicy: {{ .Values.service.vpn.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.service.vpn.port }}
      targetPort: udp-vpn
      protocol: UDP
      {{- with .Values.service.vpn.nodePort }}
      nodePort: {{ . }}
      {{- end }}
      name: udp-vpn
  selector:
    {{- include "wg-easy.selectorLabels" . | nindent 4 }}