apiVersion: v1
kind: Service
metadata:
  name: {{ include "wg-easy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
  {{- with .Values.service.ui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.ui.type }}
  externalTrafficPolicy: {{ .Values.service.ui.externalTrafficPolicy }}
  ports:
    - port: {{ .Values.service.ui.port }}
      targetPort: http-ui
      {{- with .Values.service.ui.nodePort }}
      nodePort: {{ . }}
      {{- end }}
      protocol: TCP
      name: http-ui
  selector:
    {{- include "wg-easy.selectorLabels" . | nindent 4 }}